services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: wenslo-frontend
    ports:
      - "5001:80"
    networks:
      - wenslo-network

networks:
  wenslo-network:
    driver: bridge
